version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=openfga
    ports:
      - "5432:5432"
    networks:
      - openfga

  migrate:
    depends_on:
      - postgres
    image: openfga/openfga:latest
    container_name: migrate
    command: migrate --datastore-engine postgres --datastore-uri 'postgres://postgres:password@postgres:5432/openfga?sslmode=disable'
    networks:
      - openfga

  openfga:
    depends_on:
      - postgres
      - migrate
    image: openfga/openfga:latest
    container_name: openfga
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://postgres:password@postgres:5432/openfga?sslmode=disable
      - OPENFGA_LOG_LEVEL=info
    command: run
    ports:
      - "8080:8080"
      - "8081:8081"
      - "3000:3000"
    networks:
      - openfga

networks:
  openfga: 